# 0-1背包问题



In [25]:
import numpy as np

v = np.array([60, 100, 120, 200, 220])
w = np.array([1, 2, 3, 4, 5])
n = 5
W = 10
s = np.zeros((n, W+1), dtype='i')

global v, w, s, n

def max_value(i, W):
    if i > n-1:
        return 0
    elif w[i] > W:
        return 0
    else:
        v1 = v[i] + max_value(i+1, W-w[i])
        v2 = max_value(i+1, W)
        if v1 > v2:
            s[i,W] = -w[i]
        return max(v1, v2)
    
print(max_value(0, W))
print(s)

480
[[ 0  0  0  0  0  0  0  0  0  0 -1]
 [ 0  0  0  0  0  0  0  0  0  0 -2]
 [ 0  0  0  0  0  0  0 -3 -3  0  0]
 [ 0  0  0  0 -4  0  0  0  0 -4 -4]
 [ 0  0  0  0  0 -5 -5 -5 -5 -5 -5]]
