# The N-dimensional array (narray)

`narray` 是一个多维容纳器(container)，来容纳类型(type)和大小(size)相等的元素。

`size` 属性规定了一个 `narray` 对象的维数和每维的分量长度，比如

In [8]:
import numpy as np

In [7]:
a = np.arange(32).reshape(4, 4, 2)
print(a)
print(a.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]
  [30 31]]]
(4, 4, 2)


上面的输出表示一个三维的，尺寸为$4\times4\times2$的数组， `shape` 属性输出一个长度为3的 `tuple` ，每一个分量表示对应维度的长度。

`narray` 对象可以使用类似MATLAB的索引方式，访问存储的数据。

索引不能超过size的长度和范围，可以用 `:` 来切片，类似Python内建的list和的切片

In [14]:
a[1]
a[1, 2:4, 0:2]

array([[12, 13],
       [14, 15]])

In [2]:
import numpy as np

a = np.random.randint(0, 100, 10)
b = np.random.randint(0, 10, 5)
print(a)
print(b)
print(a[b])

[24  2 36  0 88 68 59 57 86  1]
[0 4 8 6 8]
[24 88 86 59 86]
